import type { ScanResult } from "@/types/scan";
import type { WpScanResult } from "@/types/wp-scan";
import type { EmailScanResult } from "@/types/email-scan";

/* ── Domain Inspector ─────────────────────────────── */

export function domainToMarkdown(r: ScanResult): string {
  const lines: string[] = [];
  const date = new Date(r.scanDate).toLocaleString();

  lines.push(`# Domain Inspector Report: ${r.domain}`);
  lines.push(`**Score:** ${r.score}/100 (Grade ${r.grade})  `);
  lines.push(`**Scanned:** ${date}  `);
  lines.push("");

  // Quick Facts
  lines.push("## Quick Facts");
  lines.push("");
  lines.push(`| Field | Value |`);
  lines.push(`|-------|-------|`);
  lines.push(`| Registrar | ${r.quickFacts.registrar} |`);
  lines.push(`| Expires | ${r.quickFacts.expires} |`);
  lines.push(`| Domain Age | ${r.quickFacts.domainAge} |`);
  lines.push(`| NS Provider | ${r.quickFacts.nsProvider} |`);
  lines.push(`| IP Address | ${r.quickFacts.ipAddress} |`);
  lines.push(`| Hosting | ${r.quickFacts.hosting} |`);
  lines.push(`| Mail | ${r.quickFacts.mail} |`);
  lines.push(`| SSL Expires | ${r.quickFacts.sslExpires} |`);
  lines.push(`| DMARC | ${r.quickFacts.dmarc} |`);
  lines.push(`| Platform | ${r.quickFacts.platform} |`);
  if (r.quickFacts.cloudflareDns || r.quickFacts.cloudflareProxy) {
    lines.push(`| Cloudflare DNS | ${r.quickFacts.cloudflareDns ? "Active" : "Not Active"} |`);
    lines.push(`| Cloudflare Proxy | ${r.quickFacts.cloudflareProxy ? "On" : "Off"} |`);
  }
  lines.push("");

  // Score Breakdown
  lines.push("## Score Breakdown");
  lines.push("");
  for (const [cat, data] of Object.entries(r.breakdown)) {
    const label = cat.charAt(0).toUpperCase() + cat.slice(1);
    lines.push(`### ${label} (${data.earned}/${data.max})`);
    for (const item of data.items) {
      const icon = item.earned === item.max ? "\u2705" : item.earned > 0 ? "\u26A0\uFE0F" : "\u274C";
      lines.push(`- ${icon} ${item.name}: ${item.earned}/${item.max}`);
    }
    lines.push("");
  }

  // Issues
  if (r.issues.length > 0) {
    lines.push("## Issues Found");
    lines.push("");
    for (const issue of r.issues) {
      const icon = issue.severity === "critical" ? "\u274C" : issue.severity === "warning" ? "\u26A0\uFE0F" : "\u2139\uFE0F";
      lines.push(`- ${icon} **${issue.title}** — ${issue.description}`);
    }
    lines.push("");
  }

  // What to Fix
  if (r.whatToFix.length > 0) {
    lines.push("## What to Fix");
    lines.push("");
    for (const fix of r.whatToFix) {
      lines.push(`${fix.priority}. **${fix.title}** — ${fix.description}`);
    }
    lines.push("");
  }

  // Integrity
  lines.push("## Integrity");
  lines.push("");
  lines.push(`- SSL Certificate: ${r.integrity.sslCertificate}`);
  lines.push(`- SSL Issuer: ${r.integrity.sslIssuer}`);
  lines.push(`- DNSSEC: ${r.integrity.dnssec}`);
  lines.push(`- HSTS: ${r.integrity.hsts}`);
  lines.push(`- Security Headers: ${r.integrity.securityHeaders}`);
  lines.push("");

  // DNS Records
  lines.push("## DNS Records");
  lines.push("");
  lines.push(`| Record | Status |`);
  lines.push(`|--------|--------|`);
  for (const [rec, val] of Object.entries(r.dns.records)) {
    lines.push(`| ${rec.toUpperCase()} | ${val ? "\u2705 Found" : "\u274C Missing"} |`);
  }
  lines.push("");
  if (r.dns.nameservers.length > 0) {
    lines.push("**Nameservers:**");
    for (const ns of r.dns.nameservers) {
      lines.push(`- ${ns.host}`);
    }
    lines.push("");
  }

  // Audit Observations
  for (const [cat, items] of Object.entries(r.audit)) {
    if (items.length === 0) continue;
    const label = cat.charAt(0).toUpperCase() + cat.slice(1);
    lines.push(`## ${label} Audit`);
    lines.push("");
    for (const item of items) {
      const icon = item.status === "verified" ? "\u2705" : item.status === "issue" ? "\u274C" : item.status === "attention" ? "\u26A0\uFE0F" : "\u2139\uFE0F";
      lines.push(`- ${icon} **${item.title}** — ${item.detail}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(`*Generated by [xCloud Tools](https://tools.xcloud.host) — ${date}*`);

  return lines.join("\n");
}

/* ── WP Health Checker ────────────────────────────── */

export function wpToMarkdown(r: WpScanResult): string {
  const lines: string[] = [];
  const date = new Date(r.scanDate).toLocaleString();

  lines.push(`# WP Health Checker Report: ${r.domain}`);
  lines.push(`**Score:** ${r.score}/100 (Grade ${r.grade})  `);
  lines.push(`**Scanned:** ${date}  `);
  lines.push("");

  // Quick Facts
  lines.push("## Quick Facts");
  lines.push("");
  lines.push(`| Field | Value |`);
  lines.push(`|-------|-------|`);
  lines.push(`| WP Version | ${r.quickFacts.wpVersion} |`);
  lines.push(`| Theme | ${r.quickFacts.theme} |`);
  lines.push(`| PHP Version | ${r.quickFacts.phpVersion} |`);
  lines.push(`| Server | ${r.quickFacts.server} |`);
  lines.push(`| SSL | ${r.quickFacts.ssl} |`);
  lines.push(`| CDN | ${r.quickFacts.cdn} |`);
  lines.push(`| Caching | ${r.quickFacts.cachingPlugin} |`);
  lines.push(`| Plugins Detected | ${r.quickFacts.pluginCount} |`);
  lines.push("");

  // Score Breakdown
  lines.push("## Score Breakdown");
  lines.push("");
  const catLabels: Record<string, string> = {
    wpCore: "WP Core",
    plugins: "Plugins",
    loginSecurity: "Login Security",
    serverSsl: "Server & SSL",
    performance: "Performance",
    seo: "SEO",
  };
  for (const [cat, data] of Object.entries(r.breakdown)) {
    const label = catLabels[cat] || cat;
    lines.push(`### ${label} (${data.earned}/${data.max})`);
    for (const item of data.items) {
      const icon = item.earned === item.max ? "\u2705" : item.earned > 0 ? "\u26A0\uFE0F" : "\u274C";
      lines.push(`- ${icon} ${item.name}: ${item.earned}/${item.max}`);
    }
    lines.push("");
  }

  // Issues
  if (r.issues.length > 0) {
    lines.push("## Issues Found");
    lines.push("");
    for (const issue of r.issues) {
      const icon = issue.severity === "critical" ? "\u274C" : issue.severity === "warning" ? "\u26A0\uFE0F" : "\u2139\uFE0F";
      lines.push(`- ${icon} **${issue.title}** — ${issue.description}`);
    }
    lines.push("");
  }

  // What to Fix
  if (r.whatToFix.length > 0) {
    lines.push("## What to Fix");
    lines.push("");
    for (const fix of r.whatToFix) {
      lines.push(`${fix.priority}. **${fix.title}** — ${fix.description}`);
    }
    lines.push("");
  }

  // Security Headers
  if (r.securityHeaders.length > 0) {
    lines.push("## Security Headers");
    lines.push("");
    lines.push(`| Header | Status | Value |`);
    lines.push(`|--------|--------|-------|`);
    for (const h of r.securityHeaders) {
      lines.push(`| ${h.name} | ${h.present ? "\u2705 Present" : "\u274C Missing"} | ${h.value || "—"} |`);
    }
    lines.push("");
  }

  // Exposed Files
  if (r.exposedFiles.length > 0) {
    lines.push("## Sensitive File Exposure");
    lines.push("");
    for (const f of r.exposedFiles) {
      const icon = f.status === "hidden" || f.status === "not-found" ? "\u2705" : "\u274C";
      lines.push(`- ${icon} \`${f.path}\` — ${f.status}`);
    }
    lines.push("");
  }

  // Findings
  if (r.findings.length > 0) {
    lines.push("## Findings");
    lines.push("");
    for (const f of r.findings) {
      const icon = f.severity === "critical" ? "\u274C" : f.severity === "high" ? "\u26A0\uFE0F" : f.severity === "medium" ? "\u26A0\uFE0F" : "\u2139\uFE0F";
      lines.push(`- ${icon} **${f.title}** — ${f.detail}`);
    }
    lines.push("");
  }

  // Plugins
  if (r.detectedPlugins.length > 0) {
    lines.push("## Detected Plugins");
    lines.push("");
    lines.push(`| Plugin | Version | Status |`);
    lines.push(`|--------|---------|--------|`);
    for (const p of r.detectedPlugins) {
      const icon = p.status === "ok" ? "\u2705" : p.status === "vulnerable" ? "\u274C" : "\u26A0\uFE0F";
      lines.push(`| ${p.name} | ${p.version || "Unknown"} | ${icon} ${p.status} |`);
    }
    lines.push("");
  }

  // Access & API Checks
  if (r.accessChecks.length > 0) {
    lines.push("## Access & API Checks");
    lines.push("");
    for (const c of r.accessChecks) {
      const icon = c.status === "verified" ? "\u2705" : c.status === "issue" ? "\u274C" : "\u26A0\uFE0F";
      lines.push(`- ${icon} **${c.title}** — ${c.detail}`);
    }
    lines.push("");
  }

  // Version Exposure
  if (r.versionExposure.length > 0) {
    lines.push("## Version Exposure");
    lines.push("");
    for (const v of r.versionExposure) {
      const icon = v.status === "hidden" ? "\u2705" : "\u274C";
      lines.push(`- ${icon} **${v.title}** — ${v.detail}`);
    }
    lines.push("");
  }

  // Performance
  lines.push("## Performance");
  lines.push("");
  if (r.performance.ttfb !== null) lines.push(`- TTFB: ${r.performance.ttfb}ms`);
  if (r.performance.pageSize !== null) lines.push(`- Page Size: ${(r.performance.pageSize / 1024).toFixed(1)} KB`);
  lines.push(`- GZIP: ${r.performance.gzip ? "\u2705 Enabled" : "\u274C Disabled"}`);
  lines.push(`- Cache Headers: ${r.performance.cacheHeaders ? "\u2705 Present" : "\u274C Missing"}`);
  lines.push(`- CDN: ${r.performance.cdnDetected ? "\u2705 Detected" : "\u274C Not Detected"}`);
  if (r.performance.cachingPlugin) lines.push(`- Caching Plugin: ${r.performance.cachingPlugin}`);
  lines.push("");

  // SEO
  lines.push("## SEO");
  lines.push("");
  const seoChecks: [string, boolean][] = [
    ["robots.txt", r.seo.hasRobotsTxt],
    ["Sitemap", r.seo.hasSitemap],
    ["Meta Title", r.seo.hasMetaTitle],
    ["Meta Description", r.seo.hasMetaDescription],
    ["Favicon", r.seo.hasFavicon],
    ["Open Graph", r.seo.hasOpenGraph],
    ["Viewport", r.seo.hasViewport],
    ["Canonical", r.seo.hasCanonical],
    ["Robots Indexable", r.seo.robotsIndexable],
  ];
  for (const [name, ok] of seoChecks) {
    lines.push(`- ${ok ? "\u2705" : "\u274C"} ${name}`);
  }
  lines.push("");

  lines.push("---");
  lines.push(`*Generated by [xCloud Tools](https://tools.xcloud.host) — ${date}*`);

  return lines.join("\n");
}

/* ── Email DNS Checker ────────────────────────────── */

export function emailToMarkdown(r: EmailScanResult): string {
  const lines: string[] = [];
  const date = new Date(r.scanDate).toLocaleString();

  lines.push(`# Email DNS Checker Report: ${r.domain}`);
  lines.push(`**Score:** ${r.score}/100 (Grade ${r.grade})  `);
  lines.push(`**Scanned:** ${date}  `);
  lines.push("");

  // Quick Facts
  lines.push("## Quick Facts");
  lines.push("");
  lines.push(`| Field | Value |`);
  lines.push(`|-------|-------|`);
  lines.push(`| Mail Server | ${r.quickFacts.mailServer} |`);
  lines.push(`| Mail Provider | ${r.quickFacts.mailProvider} |`);
  lines.push(`| SPF | ${r.quickFacts.spfStatus} |`);
  lines.push(`| DKIM | ${r.quickFacts.dkimStatus} |`);
  lines.push(`| DMARC Policy | ${r.quickFacts.dmarcPolicy} |`);
  lines.push(`| Blacklist | ${r.quickFacts.blacklistStatus} |`);
  lines.push(`| MX Count | ${r.quickFacts.mxCount} |`);
  lines.push(`| TLS Support | ${r.quickFacts.tlsSupport} |`);
  lines.push("");

  // Score Breakdown
  lines.push("## Score Breakdown");
  lines.push("");
  const catLabels: Record<string, string> = {
    mx: "MX Records",
    spf: "SPF",
    dkim: "DKIM",
    dmarc: "DMARC",
    blacklist: "Blacklist",
  };
  for (const [cat, data] of Object.entries(r.breakdown)) {
    const label = catLabels[cat] || cat.toUpperCase();
    lines.push(`### ${label} (${data.earned}/${data.max})`);
    for (const item of data.items) {
      const icon = item.earned === item.max ? "\u2705" : item.earned > 0 ? "\u26A0\uFE0F" : "\u274C";
      lines.push(`- ${icon} ${item.name}: ${item.earned}/${item.max}`);
    }
    lines.push("");
  }

  // Issues
  if (r.issues.length > 0) {
    lines.push("## Issues Found");
    lines.push("");
    for (const issue of r.issues) {
      const icon = issue.severity === "critical" ? "\u274C" : issue.severity === "warning" ? "\u26A0\uFE0F" : "\u2139\uFE0F";
      lines.push(`- ${icon} **${issue.title}** — ${issue.description}`);
    }
    lines.push("");
  }

  // What to Fix
  if (r.whatToFix.length > 0) {
    lines.push("## What to Fix");
    lines.push("");
    for (const fix of r.whatToFix) {
      lines.push(`${fix.priority}. **${fix.title}** — ${fix.description}`);
    }
    lines.push("");
  }

  // MX Records
  if (r.mx.records.length > 0) {
    lines.push("## MX Records");
    lines.push("");
    lines.push(`**Provider:** ${r.mx.provider}  `);
    lines.push(`**Backup MX:** ${r.mx.hasBackupMx ? "Yes" : "No"}`);
    lines.push("");
    lines.push(`| Priority | Exchange | IP |`);
    lines.push(`|----------|----------|----|`);
    for (const rec of r.mx.records) {
      lines.push(`| ${rec.priority} | ${rec.exchange} | ${rec.ip || "—"} |`);
    }
    lines.push("");
  }

  // SPF
  lines.push("## SPF");
  lines.push("");
  if (r.spf.exists && r.spf.record) {
    lines.push("```");
    lines.push(r.spf.record);
    lines.push("```");
    lines.push("");
    lines.push(`- Mechanism: \`${r.spf.mechanism}\``);
    lines.push(`- Strict: ${r.spf.isStrict ? "Yes (-all)" : "No (~all)"}`);
    lines.push(`- DNS Lookups: ${r.spf.lookupCount}/10`);
    if (r.spf.includes.length > 0) {
      lines.push(`- Includes: ${r.spf.includes.map((i) => `\`${i}\``).join(", ")}`);
    }
  } else {
    lines.push("\u274C No SPF record found");
  }
  lines.push("");

  // DKIM
  lines.push("## DKIM");
  lines.push("");
  if (r.dkim.found) {
    lines.push(`**Active selectors:** ${r.dkim.activeCount}`);
    lines.push("");
    const found = r.dkim.selectors.filter((s) => s.found);
    const notFound = r.dkim.selectors.filter((s) => !s.found);
    if (found.length > 0) {
      lines.push(`\u2705 Found: ${found.map((s) => `\`${s.name}\``).join(", ")}`);
    }
    if (notFound.length > 0) {
      lines.push(`\u274C Not found: ${notFound.map((s) => `\`${s.name}\``).join(", ")}`);
    }
  } else {
    lines.push("\u274C No DKIM selectors found");
  }
  lines.push("");

  // DMARC
  lines.push("## DMARC");
  lines.push("");
  if (r.dmarc.exists && r.dmarc.record) {
    lines.push("```");
    lines.push(r.dmarc.record);
    lines.push("```");
    lines.push("");
    lines.push(`- Policy: \`${r.dmarc.policy}\``);
    if (r.dmarc.subdomainPolicy) lines.push(`- Subdomain Policy: \`${r.dmarc.subdomainPolicy}\``);
    lines.push(`- Percentage: ${r.dmarc.percentage}%`);
    lines.push(`- Reporting: ${r.dmarc.reportingEnabled ? "\u2705 Enabled" : "\u274C Disabled"}`);
    if (r.dmarc.ruaEmails.length > 0) lines.push(`- RUA: ${r.dmarc.ruaEmails.join(", ")}`);
    if (r.dmarc.rufEmails.length > 0) lines.push(`- RUF: ${r.dmarc.rufEmails.join(", ")}`);
  } else {
    lines.push("\u274C No DMARC record found");
  }
  lines.push("");

  // Blacklist
  lines.push("## Blacklist Status");
  lines.push("");
  lines.push(`**IP Checked:** ${r.blacklist.ipChecked}  `);
  lines.push(`**Lists Checked:** ${r.blacklist.listsChecked}  `);
  lines.push(`**Status:** ${r.blacklist.clean ? "\u2705 Clean" : `\u274C Listed on ${r.blacklist.blacklistedOn.length} list(s)`}`);
  if (r.blacklist.blacklistedOn.length > 0) {
    lines.push("");
    lines.push("Listed on:");
    for (const bl of r.blacklist.blacklistedOn) {
      lines.push(`- \u274C ${bl}`);
    }
  }
  lines.push("");

  lines.push("---");
  lines.push(`*Generated by [xCloud Tools](https://tools.xcloud.host) — ${date}*`);

  return lines.join("\n");
}
